"""Fix conversation relationships

Revision ID: 610ddb1e5048
Revises: 087db58b92df
Create Date: 2025-12-07 11:44:00.359250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610ddb1e5048'
down_revision: Union[str, None] = '087db58b92df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_queries')
    op.alter_column('conversation_documents', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_queries_conversation_id'), table_name='queries')
    op.drop_constraint(op.f('fk_queries_conversation_id'), 'queries', type_='foreignkey')
    op.create_foreign_key(None, 'queries', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_queries_conversation_id'), 'queries', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_queries_conversation_id'), 'queries', ['conversation_id'], unique=False)
    op.alter_column('conversation_documents', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('conversation_queries',
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_queries_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], name=op.f('conversation_queries_query_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'query_id', name=op.f('conversation_queries_pkey'))
    )
    # ### end Alembic commands ###
